### PR TITLE
Use consistent register names where free, and make trampoline its own function

### PR DESCRIPTION
**Pull request by Ericson2314**
Ok, now things get interesting. These changes don't affect the context interface at all, but change the assembly such that I can do my parameter/coroutine stuff too. I hope after this to refactor that work so it can be added to this crate without touching the context interface interfaces.

Feel free to ask any questions about why things are changed the way they are, of course :).

### CODE REVIEW

**Comment by nathan7** [comment]
Is there any reason for the filling drop? That pointer can't possibly be read from again, afaict.

**Comment by Ericson2314** [comment]
Eh sanity checking. I could make it a debug build thing or just revert it.

**Comment by Ericson2314** [comment]
Which would you like me to do / any other concerns with this?

**Comment by Ericson2314** [comment]
Ping. I've managed to upstream all my other forks for my toy OS. This is the last one :).

**Comment by nathan7** [comment]
Pong. Still super busy, sorry :(

**Comment by Ericson2314** [comment]
Understood, thanks for at least finding the time to say so :).

**Comment by Ericson2314** [comment]
Oh, and it has conflicts now so I should fix that.

**Comment by Ericson2314** [comment]
Ok, removed the filling drop, and fix the alignment issues. The build failure is due to a bug (the thing I opened and closed the recent PR for) in nightly, "2016-06-13" at least works.

**Pull request closed without merging**
