### PR TITLE
Explicitly state the contracts of Stack and GuardedStack

### LINKED ISSUE #39: Stack should be an unsafe trait
The `Stack` trait allows returning arbitrary raw pointers which can be used to write to arbitrary addresses using only safe code.

### LINKED ISSUE #40: Stack alignment
Some platforms have requirements regarding stack alignment on function entry (16 bytes for x86, x86_64 and aarch64, 8 bytes for arm). Should it be the `Stack`'s responsibility to ensure alignment or should the context initialization perform a suitable alignment (by aligning the address returned by `Stack::base`)?

### PR DESCRIPTION
**Pull request by whitequark**
Fixes #39. Fixes #40. cc @Amanieu

### CODE REVIEW

**Comment by Amanieu** [comment]
As I mentioned in #39, `Stack` should be changed to an unsafe trait since an implementation that fails to uphold the contract could lead to memory unsafety.

The alternative is to have only `GuardedStack` uphold a contract. Callers of `Generator::unsafe_new` will then have to ensure themselves that the `Stack` they pass in correctly upholds the stack requirements.

**Comment by whitequark** [comment]
> As I mentioned in #39, Stack should be changed to an unsafe trait since an implementation that fails to uphold the contract could lead to memory unsafety.

I don't see how this is true. You cannot use a Stack implementation without unsafe code.

**Comment by Amanieu** [comment]
> I don't see how this is true. You cannot use a Stack implementation without unsafe code.

Fair enough, my point is that you should add a note in the documentation of `unsafe_new` saying that the caller is responsible for ensuring that the `Stack` he is providing properly upholds its contract.

**Comment by whitequark** [comment]
@Amanieu addressed

**Comment by nathan7** [comment]
Landed :heart:

**Pull request closed without merging**
