### PR TITLE
Made Yielder constructor public. 

### PR DESCRIPTION
**Pull request by valarauca**
This helps for building co-routines on top of libfringe

### CODE REVIEW

**Comment by whitequark** [comment]
This totally breaks all safety guarantees provided by libfringe.

**Comment by valarauca** [comment]
I'm aware. But it is next to impossible to build a co-routine library ontop of libfringe in its current state without directly handing the developer using your library the yielder handle. 

In its current state the best I can do is wrap Yielder in another type and just tell who ever uses the library, oh this is magic you just need to pass to ever file descriptor you create, every mutex you create, and every channel you create. Why? Don't worry about it just do it. This feels like horrible form for presenting a clean interface to developer as a lib writer.

The other option is accept some unsafety.

**Comment by whitequark** [comment]
How exactly does your PR help here?

**Comment by valarauca** [comment]
By allowing the yielder to be constructed separately it can be placed in a thread local key. This allows for functions like `File::read`, `Receiver::read`, or `Mutex::wait` to block the without having to be explicitly passed the yielder handle as an argument. As they may call the yielder located in a thread local key. 

This allows for co-routine libraries that integrate non-blocking IO on-top of libfringe to be built on top of libfringe without the end developer knowing about the architecture of libfringe. 

In the current state libfringe cannot be abstracted away. The yielder handle must always be passed to co-routine lambdas to allow them to suspend. Anything call/function that could suspend must also be passed the yielder.

**Comment by Amanieu** [comment]
Can't you just put a raw pointer to a `Yielder` in a thread local key? This will require some unsafe code but you should be able to build a safe interface around it.

**Pull request closed without merging**
