### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by retep998**

### CODE REVIEW

**Comment by whitequark** [comment]
It is true that UMS exists but I don't believe libfringe's abstractions can be provided on top of UMS, so now the paragraph is misleading.

**Comment by retep998** [comment]
If someone can explain why UMS is unsuitable, then I'll update the paragraph to say so.

**Comment by whitequark** [comment]
As far as I understand, UMS requires setting up external global state. The way libfringe is written, all context relevant to a generator is confined within that generator (this is important both for making them composable, and for nicely cooperating on bare-metal, on SMP/AMP systems, etc.) This can be emulated with fibers, since the only non-local bit is the `ConvertThreadToFiber()` function and it's idempotent. But that is not the case with UMS.

**Comment by whitequark** [comment]
:+1:

**Pull request closed without merging**
